### ISSUE TITLE
Use EVSCL

### ISSUE THREAD

**Issue by redcatbear** [exasol/exasol-virtual-schema-lua#38]
## Situation

To unify the code base of EVSL and RLSL we need to move common parts to a library called `exasol-virtual-schema-common-lua` (EVSCL).

```[tasklist]
### Tasks
- [x] Include EVSCL
- [x] Update UML Diagrams
- [x] Fix requirement chain
```

```[tasklist]
## Dependencies
- [ ] https://github.com/exasol/exasol-virtual-schema-common-lua/issues/1
- [ ] https://github.com/exasol/exasol-virtual-schema-common-lua/issues/3
```

**Comment by ckunki** [comment]
Blocked until CW 12 2023
